name: agriteck_user
description: A new Flutter application.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  carousel_pro: ^1.0.0
  flutter_staggered_grid_view: ^0.6.2
  cupertino_icons: ^1.0.5
  font_awesome_flutter: ^10.1.0
  image_picker: ^0.8.5+3
  image_cropper: ^3.0.0
  fluttertoast: ^8.0.9
  floating_action_bubble: ^1.1.4
  tflite: any
  intl: ^0.17.0
  async_loader: ^0.1.2
  firebase_core: ^1.21.1
  firebase_auth: ^3.7.0
  pinput: ^2.2.12
  shared_preferences: ^2.0.15
  firebase_storage: ^10.3.7
  cloud_firestore: ^3.4.6
  steel_crypt: ^3.0.0+1
  path_provider: ^2.0.11
  google_fonts: ^3.0.1
  geolocator: ^9.0.1
  geocoding: ^2.0.5
  cached_network_image: ^3.2.1
  get: ^4.6.5
  dio: ^4.0.6
  syncfusion_flutter_charts: ^20.2.45
dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/diseases/
    - assets/icons/
    - assets/images/
    - assets/plants/
    - assets/
    - assets/mobilenet_model/
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
